version: "3.7"

services:
  reverse-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "rproxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
      - "./custom_config.conf:/etc/nginx/conf.d/custom_config.conf:ro"
    restart: "always"
    networks:
      - "proxy-net"
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt-helper"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "rproxy"
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    restart: "always"
    depends_on:
      - "rproxy"
    networks:
      - "proxy-net"

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  proxy-net:
    external: true
